import { db } from './src/db/index';
import { users, exercises, profiles, routines, routineExercises, nutritionLogs, weightLogs, painLogs } from './src/db/schema';

const initialExercises = [
  { id: 'e1111111-1111-1111-1111-111111111111', title: 'Neck Rotations', targetMuscle: 'Neck', equipmentNeeded: ['None'], difficulty: 'beginner' },
  { id: 'e2222222-2222-2222-2222-222222222222', title: 'Cat-Cow Stretch', targetMuscle: 'Back', equipmentNeeded: ['Mat'], difficulty: 'beginner' },
  { id: 'e3333333-3333-3333-3333-333333333333', title: 'Deadbeat Squats', targetMuscle: 'Legs', equipmentNeeded: ['Dumbbells'], difficulty: 'beginner' },
  { id: 'e4444444-4444-4444-4444-444444444444', title: 'Plank Hold', targetMuscle: 'Core', equipmentNeeded: ['Mat'], difficulty: 'intermediate' },
  { id: 'e5555555-5555-5555-5555-555555555555', title: 'Push-Ups', targetMuscle: 'Chest', equipmentNeeded: ['None'], difficulty: 'beginner' }
];

const mockUsers = [
  { id: 'user_mock_1', email: 'alex@example.com', fullName: 'Alex Rivera', role: 'user' },
  { id: 'user_mock_2', email: 'sarah@example.com', fullName: 'Sarah Jenkins', role: 'user' },
  { id: 'user_mock_3', email: 'marco@example.com', fullName: 'Marco Rossi', role: 'user' },
  { id: 'user_mock_4', email: 'coach@bekfit.com', fullName: 'Coach Bek', role: 'coach' },
];

async function seed() {
  console.log('🌱 Starting Global Seeding...');
  try {
    // 1. Seed Exercises
    console.log('-> Seeding Exercises...');
    for (const ex of initialExercises) {
      await db.insert(exercises).values(ex as any).onConflictDoNothing();
    }

    // 2. Seed Users
    console.log('-> Seeding Mock Users...');
    for (const u of mockUsers) {
      await db.insert(users).values(u as any).onConflictDoNothing();
    }

    // 3. Seed Profiles & Logs for Athletes
    console.log('-> Seeding Athletes Data (Logs, Profiles, Routines)...');
    for (const u of mockUsers.filter(user => user.role === 'user')) {
      // Profile
      await db.insert(profiles).values({
        userId: u.id,
        biologicalSex: Math.random() > 0.5 ? 'male' : 'female',
        heightCm: 170 + Math.floor(Math.random() * 20),
        weightKg: (70 + Math.random() * 15).toString(),
        activityLevel: 'active',
        fitnessGoals: ['Build Muscle', 'Mobility']
      } as any);

      // Weight Logs
      for (let i = 0; i < 5; i++) {
        await db.insert(weightLogs).values({
          userId: u.id,
          weightKg: (75 + i + Math.random()).toString(),
          createdAt: new Date(Date.now() - i * 86400000)
        } as any);
      }

      // Nutrition Logs
      await db.insert(nutritionLogs).values({
        userId: u.id,
        mealType: 'Breakfast',
        calories: 600,
        proteinG: 40,
        carbsG: 60,
        fatsG: 15
      } as any);

      // Pain Logs
      if (Math.random() > 0.7) {
        await db.insert(painLogs).values({
          userId: u.id,
          bodyPart: 'Lower Back',
          painLevel: 6,
          notes: 'Dull ache after long sitting sessions'
        } as any);
      }

      // Routines
      const routineResult = await db.insert(routines).values({
        userId: u.id,
        status: 'completed',
        isAiGenerated: true,
        notes: 'Protocol generated by Vitality Engine V3'
      } as any).returning({ id: routines.id });

      const routineId = routineResult[0].id;

      // Routine Exercises
      for (let i = 0; i < 3; i++) {
        await db.insert(routineExercises).values({
          routineId,
          exerciseId: initialExercises[i].id,
          orderIndex: i,
          sets: 3,
          reps: '12',
          rpe: 8
        } as any);
      }
    }

    console.log('✅ Global Seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seed();
